spring:
  application:
    name: umroh

  datasource:
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/dashboard-umroh}
  jpa:
    hibernate:
      ddl-auto: update

server:
  address: 0.0.0.0
  port: 8080
  
#jdbc:postgresql://localhost:5432/dashboard-umroh

jwt:
  key: ${JWT_KEY}
  access-token-expiration: 32400000 # in milliseconds 9  hour)
  refresh-token-expiration: 604800000 # in milliseconds (1 week)
